version: "3.9"

services:
  db:
    image: postgres:16
    container_name: lawyer_postgres
    restart: always
    environment:
      POSTGRES_USER: lawyer
      POSTGRES_PASSWORD: lawyerpass
      POSTGRES_DB: lawyer_booking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
